# Generated by Django 5.1.6 on 2025-02-10 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Cédula')),
                ('no_tarjeta_cr', models.CharField(max_length=20, verbose_name='Número de Tarjeta de Crédito')),
                ('limite_credito', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Límite de Crédito')),
                ('tipo_persona', models.CharField(choices=[('F', 'Física'), ('J', 'Jurídica')], max_length=1, verbose_name='Tipo de Persona')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado (Activo)')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Cédula')),
                ('tanda_labor', models.CharField(choices=[('M', 'Matutina'), ('V', 'Vespertina'), ('N', 'Nocturna')], max_length=1, verbose_name='Tanda Laboral')),
                ('porciento_comision', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje de Comisión')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado (Activo)')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado (Activo)')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='TipoCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado (Activo)')),
            ],
            options={
                'verbose_name': 'Tipo de Combustible',
                'verbose_name_plural': 'Tipos de Combustible',
            },
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado (Activo)')),
            ],
            options={
                'verbose_name': 'Tipo de Vehículo',
                'verbose_name_plural': 'Tipos de Vehículos',
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado (Activo)')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentcar_app.marca', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('no_chasis', models.CharField(max_length=50, unique=True, verbose_name='Número de Chasis')),
                ('no_motor', models.CharField(max_length=50, unique=True, verbose_name='Número de Motor')),
                ('no_placa', models.CharField(max_length=20, unique=True, verbose_name='Número de Placa')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado (Activo)')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentcar_app.marca', verbose_name='Marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentcar_app.modelo', verbose_name='Modelo')),
                ('tipo_combustible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentcar_app.tipocombustible', verbose_name='Tipo de Combustible')),
                ('tipo_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentcar_app.tipovehiculo', verbose_name='Tipo de Vehículo')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
            },
        ),
        migrations.CreateModel(
            name='Renta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_renta', models.DateField(verbose_name='Fecha de Renta')),
                ('fecha_devolucion', models.DateField(verbose_name='Fecha de Devolución')),
                ('monto_dia', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto por Día')),
                ('cantidad_dias', models.IntegerField(verbose_name='Cantidad de Días')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado (Activo)')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentcar_app.cliente', verbose_name='Cliente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentcar_app.empleado', verbose_name='Empleado')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentcar_app.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Renta',
                'verbose_name_plural': 'Rentas',
            },
        ),
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiene_ralladuras', models.BooleanField(default=False, verbose_name='Tiene Ralladuras')),
                ('cantidad_combustible', models.CharField(choices=[('1/4', '1/4 de Tanque'), ('1/2', '1/2 de Tanque'), ('3/4', '3/4 de Tanque'), ('Lleno', 'Tanque Lleno')], max_length=10, verbose_name='Cantidad de Combustible')),
                ('tiene_goma_repuesta', models.BooleanField(default=False, verbose_name='Tiene Goma de Repuesto')),
                ('tiene_gato', models.BooleanField(default=False, verbose_name='Tiene Gato')),
                ('tiene_roturas_cristal', models.BooleanField(default=False, verbose_name='Tiene Roturas de Cristal')),
                ('estado_gomas', models.JSONField(verbose_name='Estado de las Gomas')),
                ('fecha', models.DateField(verbose_name='Fecha de Inspección')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado (Activo)')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentcar_app.cliente', verbose_name='Cliente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentcar_app.empleado', verbose_name='Empleado que Realiza la Inspección')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentcar_app.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Inspección',
                'verbose_name_plural': 'Inspecciones',
            },
        ),
    ]
