# Generated by Django 5.1.6 on 2025-02-18 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcar_app', '0003_alter_vehiculo_descripcion_alter_vehiculo_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='descripcion',
            field=models.CharField(max_length=100, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado (Activo)'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentcar_app.marca', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentcar_app.modelo', verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='no_chasis',
            field=models.CharField(max_length=50, unique=True, verbose_name='Número de Chasis'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='no_motor',
            field=models.CharField(max_length=50, unique=True, verbose_name='Número de Motor'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='no_placa',
            field=models.CharField(max_length=20, unique=True, verbose_name='Número de Placa'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_combustible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentcar_app.tipocombustible', verbose_name='Tipo de Combustible'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentcar_app.tipovehiculo', verbose_name='Tipo de Vehículo'),
        ),
    ]
